-- Migrasi 75 produk dari website lama.
-- Aman dijalankan ulang karena source_key bersifat unik.

insert into public.products (
  source_key,
  legacy_id,
  name,
  description,
  price,
  category,
  images,
  poly_count,
  file_format,
  style,
  product_type,
  download_url,
  is_published,
  display_order
)
values
  (
    'original-001',
    1,
    'SWING ARM QTT',
    'Swing ARM QTT THAILAND FIZR',
    25000,
    'arm',
    '["images/arm-qtt1.webp","images/arm-qtt2.webp"]'::jsonb,
    '1K',
    'Dff, Obj',
    'Realistic',
    'premium',
    null,
    true,
    1
  ),
  (
    'original-002',
    2,
    'SWING ARM RACE PRO X01',
    'Arm CNC RACE PRO VARIO 125/150',
    25000,
    'arm',
    '["images/arm-race-pro1.webp","images/arm-race-pro2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    2
  ),
  (
    'original-003',
    3,
    'SWING ARM SIJIRO',
    'Swing Arm shijiro coax GL MAX',
    25000,
    'arm',
    '["images/arm-sijiro-coak1.webp","images/arm-sijiro-coak2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    3
  ),
  (
    'original-004',
    4,
    'SWING ARM NBR',
    'SWING ARM NBR AEROX NEW/OLD',
    25000,
    'arm',
    '["images/arm-nbr1.webp","images/arm-nbr2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    4
  ),
  (
    'original-005',
    5,
    'STABILIZER MATRIS',
    'Stabilizers Matris NINJA SS/R',
    25000,
    'aksesoris',
    '["images/matris1.webp","images/matris2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    5
  ),
  (
    'original-006',
    6,
    'COVER MESIN NINJA XYZ',
    'Manisan Ninja cover',
    25000,
    'aksesoris',
    '["images/cvr-xyz1.webp","images/cvr-xyz2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    6
  ),
  (
    'original-007',
    7,
    'TUTUP TANGKY TYGA',
    'Tutup tangki model TYGA Ninja/GL',
    20000,
    'aksesoris',
    '["images/tyga1.webp","images/tyga2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    7
  ),
  (
    'original-008',
    8,
    'BORGOL SHOCK DEPAN',
    'Bracket shock depan Ninja/RX-King',
    15000,
    'aksesoris',
    '["images/borgol-sok-depan1.webp","images/borgol-sok-depan2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    8
  ),
  (
    'original-009',
    9,
    'KNALPOT PEKAJAMAN KIDAL',
    'Knalpot knalpot Herx Hoek',
    25000,
    'mesin',
    '["images/pekajaman1.webp","images/pekajaman2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    9
  ),
  (
    'original-010',
    10,
    'RADIATOR VINS AEROX',
    'Radiator Vins Aerox Nmax',
    20000,
    'mesin',
    '["images/rd-vins1.webp","images/rd-vins2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    10
  ),
  (
    'original-011',
    11,
    'RADIATOR VND NINJA',
    'Radiator VND Ninja/MX King',
    20000,
    'mesin',
    '["images/rd-vnd1.webp","images/rd-vnd2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    11
  ),
  (
    'original-012',
    12,
    'KNALPOT DGR',
    'Knalpot Beat Karbu Road Race',
    25000,
    'mesin',
    '["images/dgr1.webp","images/dgr2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    12
  ),
  (
    'original-013',
    13,
    'VND KZR R17',
    'Velg VND KZR Ring 17 Metik disc kiri',
    25000,
    'velg',
    '["images/vnd-kzr1.webp","images/vnd-kzr2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    13
  ),
  (
    'original-014',
    14,
    'VND SIXSTARS V1',
    'Velg VND Sixstars Ring 17 Ninja/MX',
    25000,
    'velg',
    '["images/sixstar-v1.webp","images/sixstar-v2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    14
  ),
  (
    'original-015',
    15,
    'JOK NINJA SS',
    'Jok Ninja Custom Arvi',
    20000,
    'jok',
    '["images/jok-arv1.webp","images/jok-arv2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    15
  ),
  (
    'original-016',
    16,
    'JOK GL CUSTOM',
    'Jok GL custom parahu fiber',
    25000,
    'jok',
    '["images/jok-gl-set1.webp","images/jok-gl-set2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    16
  ),
  (
    'original-017',
    17,
    'JOK OZZA SUPRA X',
    'Jok Ozza Road Race Supra',
    20000,
    'jok',
    '["images/jok-ozza1.webp","images/jok-ozza2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    17
  ),
  (
    'original-018',
    18,
    'JOK MODEL SLIM FIZR',
    'Jok Fizr slim custom catur',
    20000,
    'jok',
    '["images/jok-slim1.webp","images/jok-slim2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    18
  ),
  (
    'original-019',
    19,
    'DISC MODENAS',
    'Disc Modenas style KT',
    20000,
    'velg',
    '["images/disc-modenas1.webp","images/disc-modenas2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    19
  ),
  (
    'original-020',
    20,
    'DISC PRC',
    'Piringan PRC disc kiri 260mm',
    25000,
    'velg',
    '["images/disc-prc1.webp","images/disc-prc2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    20
  ),
  (
    'original-021',
    21,
    'TB CPO',
    'Throttle Body barel CPO 30mm',
    25000,
    'mesin',
    '["images/tb-cpo1.webp","images/tb-cpo2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    21
  ),
  (
    'original-022',
    22,
    'SHOCK LCM 27',
    'Bottom shock LCM 27 Vario',
    25000,
    'sok',
    '["images/lcm1.webp","images/lcm2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    22
  ),
  (
    'original-023',
    23,
    'SHOCK 125Z + ADD',
    'Shock 125Z disc kanan',
    25000,
    'sok',
    '["images/sok-125z-1.webp","images/sok-125z-2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    23
  ),
  (
    'original-024',
    24,
    'KALIPER FJN',
    'Kaliper depan kiri FJN',
    30000,
    'sok',
    '["images/fjn1.webp","images/fjn2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    24
  ),
  (
    'original-025',
    25,
    'KALIPER 8.1',
    'Kaliper depan Formula 8.1',
    30000,
    'sok',
    '["images/kaliper-8-1-1.webp","images/kaliper-8-1-2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    25
  ),
  (
    'original-026',
    26,
    'UNDERBONE RCB MX KING',
    'Underbone RCB MX King',
    25000,
    'aksesoris',
    '["images/ub-rcb-mx1.webp","images/ub-rcb-mx2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    26
  ),
  (
    'original-027',
    27,
    'BAN MAXXIS VICTRA R17',
    'Ban Maxxis Victra ring 17',
    20000,
    'ban',
    '["images/victra1.webp","images/victra2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    27
  ),
  (
    'original-028',
    28,
    'BREAKET SELANG GORILA',
    'Bracket selang gorila clean',
    15000,
    'aksesoris',
    '["images/brkt-selang-gorila1.webp","images/brkt-selang-gorila2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    28
  ),
  (
    'original-029',
    29,
    'FAIRING HEREX',
    'Fairing Herex rangka rebah',
    20000,
    'aksesoris',
    '["images/fairing1.webp","images/fairing2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    29
  ),
  (
    'original-030',
    30,
    'BREKET HEADLAMP',
    'Bracket headlamp SJ Project',
    20000,
    'aksesoris',
    '["images/brkt-lamp1.webp","images/brkt-lamp2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    30
  ),
  (
    'original-031',
    31,
    'CVT VARIO BILLET',
    'CVT Billet Vario style Vietnam',
    55000,
    'aksesoris',
    '["images/cvt-vario-billet1.webp","images/cvt-vario-billet2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    31
  ),
  (
    'original-032',
    32,
    'ARM HYPERTECH',
    'Swing arm Hypertech Aerox',
    25000,
    'arm',
    '["images/arm-hypert1.webp","images/arm-hypert2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    32
  ),
  (
    'original-033',
    33,
    'MOUNTING VARIO MG',
    'Mounting panjang Mixiro Vario',
    25000,
    'aksesoris',
    '["images/mounting-mg1.webp","images/mounting-mg2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    33
  ),
  (
    'original-034',
    34,
    'JOK ARVI CATUR',
    'Jok Mio M3 model catur',
    20000,
    'jok',
    '["images/jok-mio1.webp","images/jok-mio2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    34
  ),
  (
    'original-035',
    35,
    'COVER FILTER VARIO BILLET',
    'Box filter billet',
    50000,
    'aksesoris',
    '["images/cvr-filter-bilet1.webp","images/cvr-filter-bilet2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    35
  ),
  (
    'original-036',
    36,
    'MASTER REM DEPAN RCB S1',
    'Master rem tabung Bonamici',
    25000,
    'aksesoris',
    '["images/rcb-s1-1.webp","images/rcb-s1-2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    36
  ),
  (
    'original-037',
    37,
    'SWING ARM DKT THAILAND',
    'Swing arm DKT Monoshock Exciter',
    40000,
    'arm',
    '["images/dkt-tai1.webp","images/dkt-tai2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    37
  ),
  (
    'original-038',
    38,
    'JOK ARVI VIETNAM',
    'Jok Vario set fiber Vietnam',
    40000,
    'jok',
    '["images/jok-viet1.webp","images/jok-viet2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    38
  ),
  (
    'original-039',
    39,
    'BAK CVT MIO',
    'Bak CVT titanium Mio',
    65000,
    'aksesoris',
    '["images/cvt-mio1.webp","images/cvt-mio2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    39
  ),
  (
    'original-040',
    40,
    'RIMS JRP TROMOL BECAK',
    'rim set tromol becak non metik ring 17',
    25000,
    'velg',
    '["images/jrp-rims1.webp","images/jrp-rims2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    40
  ),
  (
    'original-041',
    41,
    'KNALPOT MIO MEDWICK',
    'KNALPOT CEKSLIS FOR MIO',
    25000,
    'mesin',
    '["images/medwik1.webp","images/medwik2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    41
  ),
  (
    'original-042',
    42,
    'SHOCK RT STAGE SET KALIPER',
    'SHOCK RT STAGE 8 SET KALIPER SWITS',
    60000,
    'sok',
    '["images/rtstage2.webp","images/rtstage1.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    42
  ),
  (
    'original-043',
    43,
    'SHOCK LCM SET',
    'SHOCK LCM SET KALIPER DAN PIRINGAN',
    60000,
    'sok',
    '["images/sok-lcm-set1.webp","images/sok-lcm-set2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    43
  ),
  (
    'original-044',
    44,
    'SHOCK JRP THAILAND',
    'SHOCK JRP WAVE SET KALIPER',
    65000,
    'sok',
    '["images/jrp-wave1.webp","images/jrp-wave2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    44
  ),
  (
    'original-045',
    45,
    'BAN ESR',
    'BAN ESR MALAY RING 17',
    15000,
    'ban',
    '["images/ban-esr-malay1.webp","images/ban-esr-malay2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    45
  ),
  (
    'original-046',
    405,
    'VELG VND AK55 V2',
    'VND AK55 V2 RING 17',
    25000,
    'velg',
    '["images/vnd-ak55-v2-1.webp","images/vnd-ak55-v2-2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    46
  ),
  (
    'original-047',
    406,
    'DISC DT10',
    'DISC BUTA DT10 VIET STYLE',
    25000,
    'velg',
    '["images/disc-dt10-1.webp","images/disc-dt10-2.webp"]'::jsonb,
    '1K',
    'Dff, OBJ',
    'Stylized',
    'premium',
    null,
    true,
    47
  ),
  (
    'original-048',
    45,
    'VELG VND SET BAN',
    'VELG VND NEW SPEED R17 FOR MX KING DAN SEJENISNYA',
    0,
    'velg',
    '["images/velg-vnd-free1.webp","images/velg-vnd-free2.webp"]'::jsonb,
    '800',
    'OBJ',
    'Sport',
    'free',
    'https://sfl.gl/zRU4',
    true,
    48
  ),
  (
    'original-049',
    46,
    'FRAME PLAT HTS',
    'HAHA HTS KASIAN WKWK',
    0,
    'aksesoris',
    '["images/plat1.webp","images/plat2.webp"]'::jsonb,
    '800',
    'OBJ',
    'soft',
    'free',
    'https://sfl.gl/UkDj2DN',
    true,
    49
  ),
  (
    'original-050',
    47,
    'KALIPER GROZA',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'sok',
    '["images/kaliper-groza-free1.webp","images/kaliper-groza-free2.webp"]'::jsonb,
    '800',
    'OBJ',
    'soft',
    'free',
    'https://sfl.gl/hO9Pp',
    true,
    50
  ),
  (
    'original-051',
    48,
    'VELG VND BINTANG LAUT',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'velg',
    '["images/bintanglaut1.webp","images/bintanglaut2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/V6a6x0',
    true,
    51
  ),
  (
    'original-052',
    49,
    'BAK CVT DT10',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'aksesoris',
    '["images/cvt-dt10-1.webp","images/cvt-dt10-2.webp"]'::jsonb,
    '800',
    'OBJ',
    'recing',
    'free',
    'https://sfl.gl/kYn6tfU',
    true,
    52
  ),
  (
    'original-053',
    50,
    'SHOCK BUBUT THAILAND',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'sok',
    '["images/sokbubut1.webp","images/sokbubut2.webp"]'::jsonb,
    '800',
    'OBJ',
    'recing',
    'free',
    'https://sfl.gl/G0uq',
    true,
    53
  ),
  (
    'original-054',
    51,
    'CVT AIRBLADE',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'aksesoris',
    '["images/cvt-airblade.webp","images/cvt-airblade2.webp"]'::jsonb,
    '800',
    'OBJ',
    'recing',
    'free',
    'https://sfl.gl/vdni',
    true,
    54
  ),
  (
    'original-055',
    52,
    'FOOTSTEP SKUPI',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'aksesoris',
    '["images/step-skupi.webp","images/step-skupi2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/HFw0v',
    true,
    55
  ),
  (
    'original-056',
    53,
    'DISC GALFER',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'velg',
    '["images/disc-galver1.webp","images/disc-galver2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/b3KRv',
    true,
    56
  ),
  (
    'original-057',
    54,
    'BAN KINGLAND VELLOX CTX',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'ban',
    '["images/ban-drag1.webp","images/ban-drag2.webp"]'::jsonb,
    '800',
    'OBJ',
    'resing abieezz',
    'free',
    'https://sfl.gl/JojuTd',
    true,
    57
  ),
  (
    'original-058',
    55,
    'SHOCK GROZA',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'sok',
    '["images/shock-groza1.webp","images/shock-groza2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/2h82uwWl',
    true,
    58
  ),
  (
    'original-059',
    56,
    'TUTUP OLI CNC',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'aksesoris',
    '["images/tutup-oli-cnc1.webp","images/tutup-oli-cnc2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/3w0W67Yu',
    true,
    59
  ),
  (
    'original-060',
    57,
    'SWING ARM SHIJIRO EXTREME',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'aksesoris',
    '["images/arm-sijiro-extreme1.webp","images/arm-sijiro-extreme2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/2HDGf',
    true,
    60
  ),
  (
    'original-061',
    58,
    'BAN MP76 R17',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'ban',
    '["images/ban-mp76-1.webp","images/ban-mp76-2.webp"]'::jsonb,
    '800',
    'OBJ',
    'resing',
    'free',
    'https://sfl.gl/6yIijD',
    true,
    61
  ),
  (
    'original-062',
    59,
    'SHOCK OHLINS',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'sok',
    '["images/sok-ohlins1.webp","images/sok-ohlins2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/vMB2z',
    true,
    62
  ),
  (
    'original-063',
    60,
    'VELG CMG XMODE',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'velg',
    '["images/cmgxmode1.webp","images/cmgxmode2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/WuyJ9o',
    true,
    63
  ),
  (
    'original-064',
    61,
    'HUGGER PENDEK',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'aksesoris',
    '["images/hugger1.webp","images/hugger2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/lfPQj',
    true,
    64
  ),
  (
    'original-065',
    62,
    'KNALPOT PEKAJAMAN TITANIUM',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'mesin',
    '["images/pekajamanjupe1.webp","images/pekajamanjupe2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/E1TOHTQ',
    true,
    65
  ),
  (
    'original-066',
    63,
    'RADIATOR GSX PNP VARIO',
    'PNP SENDIRI YA JANGAN MANJA',
    0,
    'mesin',
    '["images/rdgsx1.webp","images/rdgsx2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/M1n7Mpsn',
    true,
    66
  ),
  (
    'original-067',
    64,
    'STRIPING AEROX CUSTOM BLUE',
    'PNP BASE BRODEE22',
    0,
    'strip',
    '["images/aeroks1.webp","images/aeroks2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/w7X9tKH',
    true,
    67
  ),
  (
    'original-068',
    65,
    'STRIPING AEROX HITAM UNGU',
    'PNP BASE BRODEE22',
    0,
    'strip',
    '["images/aerox-hitam1.webp","images/aerox-hitam2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/FY2q74',
    true,
    68
  ),
  (
    'original-069',
    66,
    'STRIPING VIETNAM STYLE',
    'PNP BASE BRODEE22',
    0,
    'strip',
    '["images/aerox-merah1.webp","images/aerox-merah2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/FY2q74',
    true,
    69
  ),
  (
    'original-070',
    67,
    'STRIPING AEROX VIETNAM STYLE',
    'PNP BASE BRODEE22',
    0,
    'strip',
    '["images/aerox-merah1.webp","images/aerox-merah2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/FY2q74',
    true,
    70
  ),
  (
    'original-071',
    68,
    'STRIPING BEAT ESP TURBO',
    'PNP BASE BRODEE22',
    0,
    'strip',
    '["images/beat-esp1.webp","images/beat-esp2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/k0uRdX',
    true,
    71
  ),
  (
    'original-072',
    69,
    'STRIPING VARIO GEN2 STYLE KT',
    'PNP BASE KOCIN',
    0,
    'strip',
    '["images/gen-2-1.webp","images/gen-2-2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/HDgJEgOq',
    true,
    72
  ),
  (
    'original-073',
    70,
    'STRIPING VARIO LED NEW VIET STYLE',
    'PNP BASE BRODEE22',
    0,
    'strip',
    '["images/led-new-kuning1.webp","images/led-new-kuning2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/eNzjCU',
    true,
    73
  ),
  (
    'original-074',
    71,
    'STRIPING GEN 2 BIRU HITAM',
    'PNP BASE KOCIN',
    0,
    'strip',
    '["images/v-gen2-1.webp","images/v-gen2-2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/dRASq',
    true,
    74
  ),
  (
    'original-075',
    72,
    'STRIPING VARIO LED NEW API',
    'PNP BASE BRODEE22',
    0,
    'strip',
    '["images/vario-led-new1.webp","images/vario-led-new2.webp"]'::jsonb,
    '800',
    'OBJ',
    'proper',
    'free',
    'https://sfl.gl/fA99kXY',
    true,
    75
  )
on conflict (source_key) do update set
  legacy_id = excluded.legacy_id,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  category = excluded.category,
  images = excluded.images,
  poly_count = excluded.poly_count,
  file_format = excluded.file_format,
  style = excluded.style,
  product_type = excluded.product_type,
  download_url = excluded.download_url,
  is_published = excluded.is_published,
  display_order = excluded.display_order,
  updated_at = now();
